version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - social-network-network

  extraction:
    build:
      context: ./extraction
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - social-network-network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "4200:80"
    networks:
      - social-network-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - social-network-network

volumes:
  mongodb_data:

networks:
  social-network-network:
    driver: bridge